apiVersion: v1
kind: ConfigMap
metadata:
  name: netbox-webhook-dist-client-config
data:
  config.yaml: |
    recipients:
    - name: "baremetal_temper"
      url: "http://test.com/webhook"
      netbox_webhooks:
        device:
        - "created"
        - "updated"
        - "deleted"
    - name: "test02"
      url: "http://test.com/webhook"
      netbox_webhooks:
        site:
        - "created"
        - "updated"
        - "deleted"
        device:
        - "deleted"