{{- if .Values.nats.jetstream.fileStorage.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: netbox-webhook-dist-nats-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
{{- end }}