distributor_list:
  - name: "test01"
    url: "http://test.com/webhook"
    netbox_webhooks:
      site:
        - "created"
        - "updated"
        - "deleted"
      device:
        - "deleted"
  - name: "test02"
    url: "http://test.com/webhook"
    netbox_webhooks:
      site:
        - "created"
        - "updated"
        - "deleted"
      device:
        - "deleted"
